# Generated by Django 6.0.4 on 2026-04-11 21:05

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('TECH', 'Tech'), ('MUSIC', 'Music'), ('ART', 'Art'), ('FOOD', 'Food'), ('SPORTS', 'Sports'), ('BUSINESS', 'Business'), ('WORKSHOP', 'Workshop')], max_length=20)),
                ('event_name', models.CharField(max_length=150)),
                ('event_date', models.DateField()),
                ('event_description', models.TextField()),
                ('event_location', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event_image', models.ImageField(null=True, upload_to=main_app.models.generate_unique_name)),
                ('event_price', models.PositiveIntegerField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('event_slots', models.PositiveIntegerField()),
                ('booked_slots', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
