# Generated by Django 5.1.4 on 2024-12-09 09:00

import django.db.models.deletion
import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.CharField(max_length=120)),
                ('event_name', models.CharField(max_length=80)),
                ('event_date', models.DateField()),
                ('event_description', models.TextField()),
                ('event_location', models.CharField(max_length=80)),
                ('event_time', models.CharField(max_length=8)),
                ('event_image', models.ImageField(null=True, upload_to=main_app.models.generate_unique_name)),
                ('event_price', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.events')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
    ]
