# Generated by Django 5.1.4 on 2024-12-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_tickets_number_of_tickets_payments'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payments',
            table='payments',
        ),
    ]
