# Generated by Django 5.1.4 on 2024-12-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_payments_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='tickets',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
