# Generated by Django 5.1.4 on 2024-12-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_payments_tickets_delete_tickets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
