# Generated by Django 5.1.4 on 2024-12-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_registration_payments'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registration',
            table='registration',
        ),
    ]
