# Generated by Django 5.1.4 on 2024-12-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_registration_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='event_name',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
